platform :ios, '17.0'

target 'nante' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nante
  pod 'GoogleMLKit/Translate'

  target 'nanteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nanteUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      end
    end
  end
end
