# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nante' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nante
  pod 'GoogleMLKit/Translate'

  target 'nanteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nanteUITests' do
    # Pods for testing
  end

end
